version: '3.3'

services:

  pg:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
    volumes:
      - pg-data:/var/lib/postgresql/data

  webapp:
    image: jfahrer/demo_web_app:wait_for_pg
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD 
      - POSTGRES_HOST 
    depends_on:
      - pg

  lb:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 80:80
    environment:
      - PROXY_UPSTREAM
      - PROXY_PROTOCOL
    depends_on:
      - webapp

volumes:
  pg-data: